Added and translated documentation, better logs

diff --git a/conf/backup-with-restic b/conf/backup-with-restic
--- a/conf/backup-with-restic
+++ b/conf/backup-with-restic
@@ -3,11 +3,10 @@
 errors=""
 current_date=$(date +"%y%m%d_%H%M")
 log_file="/var/log/__APP__/${current_date}.log"
-err_file="/var/log/__APP__/${current_date}.err"
 mkdir -p "/var/log/__APP__"
 
 filter_hooks() {
-    ls /usr/share/yunohost/hooks/backup/ | grep "\-$1_" | cut -d"-" -f2 | uniq 2>> "$err_file"
+    ls /usr/share/yunohost/hooks/backup/ | grep "\-$1_" | cut -d"-" -f2 | uniq 2>&1
 }
 
 sudo yunohost app setting __APP__ last_run -v "${current_date}"
@@ -20,7 +19,7 @@ export BACKUP_CORE_ONLY
 # Backup system part conf
 conf=$(sudo yunohost app setting __APP__ conf)
 if [[ "$conf" = "1" ]]; then
-    if ! sudo yunohost backup create -n auto_conf --method __APP___app --system $(filter_hooks conf) 2>> "$err_file" >> "$log_file" ; then
+    if ! sudo yunohost backup create -n auto_conf --method __APP___app --system $(filter_hooks conf) >> "$log_file" 2>&1 ; then
         errors+="\nThe backup miserably failed to backup system configurations."
     fi
 fi
@@ -28,7 +27,7 @@ fi
 # Backup system data
 data=$(sudo yunohost app setting __APP__ data)
 if [[ "$data" = "1" ]]; then
-    if ! sudo yunohost backup create -n auto_data --method __APP___app --system $(filter_hooks data) 2>> "$err_file" >> "$log_file" ; then
+    if ! sudo yunohost backup create -n auto_data --method __APP___app --system $(filter_hooks data) >> "$log_file" 2>&1 ; then
         errors+="\nThe backup miserably failed to backup system data."
     fi
 fi
@@ -83,16 +82,16 @@ for application in $(sudo ls /etc/yunohost/apps/); do
     fi
 
     # Execute backup
-    if ! sudo yunohost backup create -n "auto_$application" --method __APP___app --apps "$application" 2>> "$err_file" >> "$log_file"; then
+    if ! sudo yunohost backup create -n "auto_$application" --method __APP___app --apps "$application" >> "$log_file" 2>&1; then
         errors+="\nThe backup miserably failed to backup $application application."
     fi
 done
 
 #=============================================
-# SEND MAIL TO NOTIFY ABOUT  FAILED OPERATIONS
+# SEND MAIL TO NOTIFY ABOUT FAILED OPERATIONS
 #=============================================
 
-partial_errors="$(cat "$log_file" | grep -E "Error|Skipped")"
+partial_errors="$(grep -iE "Error|Skipped|Warning|Fatal|Fail" "$log_file")"
 if [ -n "$partial_errors" ]; then
     errors+="\nSome backup partially failed:\n$partial_errors"
 fi
@@ -102,7 +101,7 @@ domain=$(hostname)
 repository="$(sudo yunohost app setting __APP__ repository)"
 if [[ -n "$errors" ]]; then
     sudo yunohost app setting __APP__ state -v "failed"
-    cat <(echo -e "$errors\n\n\n") "$log_file" "$err_file" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "[__APP__] Backup failed from $domain onto $repository" root
+    echo -e "$errors\n\n\n$(cat "$log_file")" | mail -a "Content-Type: text/plain; charset=UTF-8" -s "[__APP__] Backup failed from $domain onto $repository" root
 else
     sudo yunohost app setting __APP__ state -v "successful"
 fi
